name: terraform pipeline automation

on:
    push:
        branches:
            - main
            - master



env:
    TF_VAR_app_vm_size: "Standard_D2_v4"
    TF_VAR_db_vm_size: "Standard_D2_v4"
    TF_VAR_vm_username: "cld_admin"
    TF_VAR_vm_password: ${{ secrets.VM_PASSWORD }}
    TF_VAR_db_username: "db_admin"
    TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
    ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    ARM_TENANT_ID: "980a9497-3393-4e89-9671-4f0f938006fe"
    ARM_SUBSCRIPTION_ID: "f5a72aa1-60c1-4225-90ba-4e5273d6af91"



jobs:
    terraform_plan:
        name: "terraform Plan"
        runs-on: self-hosted
        steps:
            - name: "Checkout code"
              uses: actions/checkout@v3

        
            - name: "Login to Azure Subscription"
              uses: azure/login@v2
              with:
                # client-id: ${{ secrets.CLIENT_ID }}
                # tenant-id: ${{ env.ARM_TENANT_ID }}
                # subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
                # client-secret: ${{ secrets.CLIENT_SECRET }}

                creds: ${{secrets.AZURE_SECRETS}}

            - name: "Setup Terraform environment"
              uses: hashicorp/setup-terraform@v3

            - name: Azure CLI script
              uses: azure/cli@v2
              with:
                azcliversion: latest
                inlineScript: |
                    az account show    
            # - run: |
            #     echo "Checking access to the storage account container..."
            #     az storage container list \
            #         --account-name "tfstateshubham" \
            #         --auth-mode login

            # - run: az login --tenant "980a9497-3393-4e89-9671-4f0f938006fe"

            - name: "Terraform init"
              run: TF_LOG=DEBUG terraform init

            - name: Terraform Plan
              run : terraform plan -out="plan.tfplan"

            - name: View plan file
              run: terraform show plan.tfplan